export const ORDER_PAGE_LABELS = {
  FILTER: "Filter",
  SUGAR_FREE: "Sugar Free",
  TYPE: "Type",
  ALL: "All",
  YES: "Yes",
  NO: "No",
  VEG: "Veg",
  NONVEG: "Nonveg",
  APPLY: "Apply",
  CLEAR: "Clear",
  PAYMENT_METHOD: "Payment Method",
  CASH_ON_DELIVERY: "Cash on Delivery",
  ONLINE_PAYMENT: "Online Payment",
  DELIVERY: "Delivery",
  HOME_DELIVERY: "Home Delivery",
  PICKUP_FROM_STORE: "Pickup from Store",
  CHOOSE_YOUR_FOOD: "Choose Your Food",
  INGREDIENTS: "Ingredients",
  FOOD_TYPE: "Type",
  SUGAR_FREE_LABEL: "Sugar Free",
  PRICE: "Price",
  ADD_TO_CART: "Add to Cart",
  PROCEED_TO_CHECKOUT: "Proceed to Checkout",
  ITEMS: "items",
  COD: "COD",
  ONLINE: "Online",
  SELECTED_FOOD_ITEMS: "Selected Food Items",
  SUBSCRIPTION_DURATION: "Subscription Duration",
  SELECTED_ITEMS: "Selected Items",
  CLOSE: "Close",
  CONFIRM_ORDER: "Confirm Order",
};